### ISSUE TITLE
Not compatible with WebStorm 2020.2?

### ISSUE THREAD

**Issue by liamjones** [crazyproger/Tabdir#25]
Have just upgraded and I'm getting:
>11:56	Plugin Error: Plugin "Tabdir" is incompatible (marked as broken).

**Comment by vlascik** [comment]
judging by the (lack of) activity on author's repos, this will probably require a fork

**Comment by ussher** [comment]
Hope someone who can fork it does.  In the mean time I'm staying on 2020.1.  Not having this plugin effects usability for me.

**Comment by vlascik** [comment]
Seems that I managed to fix the problem somehow, https://github.com/crazyproger/Tabdir/pull/26 .

Enjoy.

**Comment by bazzik** [comment]
@vlascik
Downloaded the same day but installed only now (~15 mins ago). So far it works just fine here in PhpStorm 2020.2.2 x64 on Windows 10.

Thanks a lot!

**Comment by AndreiShostik** [comment]
also on Windows OS but unfortunately after applying this patch WebStorm isn't loaded so had to disable the plugin.
